name: CI Workflow
on:
  # Run this workflow every time a new commit pushed to upstream/fork repository.
  # Run workflow on fork repository will help contributors find and resolve issues before sending a PR.
  push:
  pull_request:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    name: test interface
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.20.14
      - name: Run go build
        run: go build cmd/mobaxterm-keygen/mobaxterm-keygen.go
      - name: Run mobaxterm-keygen
        run: ./mobaxterm-keygen -h
