name: build Release
on:
  release:
    types:
      - published
jobs:
  release-assests:
    name: release authorization
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - mobaxterm-keygen
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.20.14
      - name: Make build assets
        run: make build OS=${{ matrix.os }} ARCH=${{ matrix.arch }}
      - name: Make package assets
        run: make package OS=${{ matrix.os }} ARCH=${{ matrix.arch }}
      - name: Upload assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: _output/release/*.tgz;_output/release/*.tgz.sha256
          repo-token: ${{ secrets.GITHUB_TOKEN }}